# Generated by Django 2.0.5 on 2018-05-29 00:10


from django.db import migrations, models

import json
from minerals8.models import Mineral


def add_minerals(apps, schema_editor):
    with open('minerals8/minerals.json') as f:
        data = json.load(f)
    for da in data:
        default =''
        Mineral.objects.create(
            name = da['name'],
            image_filename = da['image filename'],
            image_caption = da['image caption'],
            category = da['category'],
            formula = da.get('formula', default),
            strunz_classification = da.get('strunz classification', default),
            color = da.get('color', default),
            crystal_system = da.get('crystal_system', default),
            unit_cell = da.get('unit cell', default),
            crystal_symmetry = da.get('crystal symmetry', default),
            cleavage =  da.get('cleavage', default),
            mohs_scale_hardness = da.get('mohs scale hardness', default),
            luster = da.get('luster', default),
            streak = da.get('streak', default),
            diaphaneity = da.get('diaphaneity', default),
            optical_properties = da.get('optical_properties', default),
            refractive_index = da.get('refractive index', default),
            crystal_habit = da.get('crystal habit', default),
            specific_gravity =  da.get('specific gravity', default),
            group = da['group']

            )



class Migration(migrations.Migration):

    dependencies = [
        ('minerals8', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_minerals)
    ]
